### ISSUE TITLE
CSV data parsing

### ISSUE THREAD

**Issue by ASTPMeetup** [codeforkansascity/meep#39]

**Comment by josiah14** [comment]
It looks like the current data is in XLSX format.  Is this story intended to extend the current capabilities to be able to *also* handle CSV formats?

**Comment by u1813292** [comment]
Hi, is this still available? I would love to work on it!

**Comment by Nicekor** [comment]
Can I have more information about this?

**Comment by krisstee** [comment]
Closing since this is addressed in the backend.
