### ISSUE TITLE
Style DateRangeSlider.js component to match uxpin design

### ISSUE THREAD

**Issue by ASTPMeetup** [codeforkansascity/meep#49]

**Comment by yanmeng26** [comment]
Hi, do you have link for your uxpin design ? 
thanks

**Comment by galbwe** [comment]
Yes. Here you go:
https://preview.uxpin.com/3ebaab4bf3defd232e90c32218050bb67db4e8bb#/pages//simulate/no-panels

**Comment by krisstee** [comment]
This seems to have already been addressed. Will be closing the issue.
