### ISSUE TITLE
how to build 

### ISSUE THREAD

**Issue by yanmeng26** [codeforkansascity/meep#51]
Hi,
I am interested in this project and I want to learn more  to see if I can contribute to some issues.
can you explain how to build it ? since there is no instruction about building in readme.md

**Comment by evanharmon1** [comment]
Hello. Glad to hear you are interested in helping out. Check out the backend repo for instructions on how to build the backend part at https://github.com/codeforkansascity/meep-backend

**Comment by yanmeng26** [comment]
Hi, how about front end?

**Comment by galbwe** [comment]
@yanmeng26 Yes that is correct.

**Comment by clementkng** [comment]
@evanharmon1 @galbwe Are there any specific instructions in the backend build regarding running this project on WSL on Windows 10? When I attempt to instructions under the docker section, I get stuck after the `docker run -p 8001:8000 meep-backend:gunicorn` step and localhost does not connect.
![image](https://user-images.githubusercontent.com/24197092/58303454-08123e80-7da5-11e9-8aca-4bb2d3285527.png)

**Comment by galbwe** [comment]
@clementkng I don't think anyone has tried running it using WSL yet. If you do ```docker container ls``` again, does it say that the container is running, or did it crash and exit?

**Comment by galbwe** [comment]
@clementkng I don't think anyone has tried it using WSL yet, so there is no specific documentation for that. 

To clarify, is the problem that the container is running when you try to connect, but not responding, or is it that the app crashes and the container is destroyed when you try to run it? 

When running the app from windows 10 using powershell in admin mode, we've found that sometimes you need to restart docker before it will work, as discussed in [this thread](https://github.com/docker/for-win/issues/2722). Not sure if it applies here, but it can't hurt to try.

Let us know if you still can't get up and running and we can try to figure something out.

**Comment by clementkng** [comment]
@galbwe Thanks for responding!

I believe the container is running, but it isn't responding. When running from Powershell in admin mode, running `docker container ls` from another window shows that the container is up, but localhost is still refusing to connect. Running `docker restart` with the container name also has no effect.

**Comment by galbwe** [comment]
@clementkng Okay. If the container is running, try doing ```docker logs <container name>```. What output do you get?

**Comment by clementkng** [comment]
@galbwe I realized that `docker run hello-world` was not working, so I suspect something is fundamentally wrong w/ my docker setup. I'll try resolving my setup for now and will come back to this if I get similar errors. Thanks for all your help!

**Comment by galbwe** [comment]
@clementkng It could be something like running linux containers vs. windows containers. Also see [here](https://stackoverflow.com/questions/49693353/error-response-from-daemon-driver-failed-programming-external-connectivity-on-e?rq=1). Their error looked similar to yours. 

Good luck!

**Comment by clementkng** [comment]
@galbwe I was able to reinstall docker, verify that the backend works, and got to the sequence of instructions to build out the frontend. In the `meep` directory, I run `npm init`, then `npm install`, but when I run `npm run dev-server` I get an npm error saying that I have a `missing script: dev-server`.

I've tried installing the dev-server package and tinkering w/ the package.json, but haven't had any luck on being able to run this command successfully. Is there a step I missed somewhere?

**Comment by galbwe** [comment]
@clementkng I updated the readme with installation instructions. Let us know if that works. You might want to do a ```git pull``` first to grab an import fix I just made.

**Comment by clementkng** [comment]
@galbwe Thanks very much, I have a local build working now!

**Comment by galbwe** [comment]
@clementkng You are welcome. If you have any questions about project structure (or lack thereof), don't hesitate to ask.

**Comment by Spechal** [comment]
Instructions included in #55 and #67

**Comment by krisstee** [comment]
Closed since this seems to be resolved. Pinned issue for future reference.
